### ISSUE TITLE
Syntax Question

### ISSUE THREAD

**Issue by HanniAbu** [Gigacore/gBoxShadow#12]
I just forked this project and when I opened it I see a lot of this: lib$es6$promise$asap

I have never seen the use of this combination of characters. Why such complicated names? And why not shorten them? I honestly have no idea what I'm looking at right now so please help me understand as I'd like to try and further build upon this.

I am a very junior programmer so please forgive me if this is crazy question.

Thanks Santhosh

**Comment by Gigacore** [comment]
Hi HanniAbu,

First of all, thanks for forking the plugin and appreciate your interest in exploring the code. The part of the code you are seeing is part of "es6-promise" polyfill that normalizing library that I am using to build this plugin.

More on es6-promise -- https://github.com/jakearchibald/es6-promise

I am using gyronorm.js that normalizes the gyroscope / accelerometer data across various devices and browsers. And this nifty library uses ECMAScript 6 Promises for staying current with standards.

So the syntax you see belongs to the newer version of Javascript -- ES6.

Hope that makes sense. Let me know if you have any questions.

Thanks,
Santhosh

**Comment by HanniAbu** [comment]
Thanks for the quick reply,  I shall look more into Promises.
